### ISSUE TITLE
Cannot get unread email list if "Check all unread emails" is used

### ISSUE THREAD

**Issue by borik** [mooz/gpum#12]
The error source probably the URL composition in line 122:
```javascript
get atomURL() this.mailURL + "feed/atom" + this.atomLabel,
```
The **"feed/atom"** string is concatenated with the label (which is "unread" if this option is set), and the resulting address ends with **"feed/atomunread"**. GMail returns usual HTML page instead of RSS, and parsing fails.

The solution would probably be adding a slash at the end of the **"feed/atom"**:

```javascript
get atomURL() this.mailURL + "feed/atom/" + this.atomLabel,
```

**Comment by mooz** [comment]
Thx for the report!
